### ISSUE TITLE
Starting a read-only pier aborts

### ISSUE THREAD

**Issue by jfranklin9000** [urbit/urbit#1624]
This is a pathological case but it aborts.
```
urbit -F zod
^d
chmod -w zod
urbit zod
~
urbit 0.8.1
boot: home is /Users/john/urbit/test/zod
loom: mapped 2048MB
lite: arvo formula 99d9974
lite: core 717aac08
lite: final state 717aac08
loom: mapped 2048MB
address 0x68 out of loom!
loom: [0x200000000 : 0x280000000)
Assertion '0' failed in noun/events.c:129

bail: oops
bailing out
Assertion failed: (0), function u3m_bail, file noun/manage.c, line 663.
boot: protected loom
live: loaded: MB/259.981.312
boot: installed 262 jets
Abort trap: 6 (core dumped)
```
At boot time we should check permissions of everything urbit writes.

**Comment by joemfb** [comment]
Can you get a backtrace out of that coredump?

**Comment by ohAitch** [comment]
Re: pathological, probably the most impactful thing in this vicinity is
making sure to abort cleanly if there's like a block error and the FS
remounts itself read-only.

**Comment by jfranklin9000** [comment]
```
lldb urbit
(lldb) target create "urbit"
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
Current executable set to 'urbit' (x86_64).
(lldb) run zod
Process 7774 launched: '/Users/jmf/.nix-profile/bin/urbit' (x86_64)
~
urbit 0.8.1
boot: home is /Users/jmf/coredump/zod
loom: mapped 2048MB
lite: arvo formula 99d9974
lite: core 717aac08
lite: final state 717aac08
loom: mapped 2048MB
address 0x68 out of loom!
loom: [0x200000000 : 0x280000000)
Assertion '0' failed in noun/events.c:129

bail: oops
bailing out
Assertion failed: (0), function u3m_bail, file noun/manage.c, line 663.
Process 7774 stopped
* thread #2, stop reason = signal SIGABRT
    frame #0: 0x00007fff753202c6 libsystem_kernel.dylib`__pthread_kill + 10
libsystem_kernel.dylib`__pthread_kill:
->  0x7fff753202c6 <+10>: jae    0x7fff753202d0            ; <+20>
    0x7fff753202c8 <+12>: movq   %rax, %rdi
    0x7fff753202cb <+15>: jmp    0x7fff7531a457            ; cerror_nocancel
    0x7fff753202d0 <+20>: retq
Target 0: (urbit) stopped.
boot: protected loom
live: loaded: MB/259.981.312
boot: installed 262 jets
(lldb) bt
* thread #2, stop reason = signal SIGABRT
  * frame #0: 0x00007fff753202c6 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff753dbbf1 libsystem_pthread.dylib`pthread_kill + 284
    frame #2: 0x00007fff7528a6a6 libsystem_c.dylib`abort + 127
    frame #3: 0x00007fff7525320d libsystem_c.dylib`__assert_rtn + 324
    frame #4: 0x0000000100034f0f urbit`u3m_bail + 367
    frame #5: 0x000000010003516e urbit`c3_cooked + 14
    frame #6: 0x0000000100028f47 urbit`u3e_fault + 407
    frame #7: 0x0000000100053c0d urbit`catch_exception_raise + 269
    frame #8: 0x00007fff75324295 libsystem_kernel.dylib`_Xexception_raise + 156
    frame #9: 0x00007fff75324531 libsystem_kernel.dylib`exc_server + 80
    frame #10: 0x000000010005402b urbit`mach_exception_thread + 107
    frame #11: 0x00007fff753d92eb libsystem_pthread.dylib`_pthread_body + 126
    frame #12: 0x00007fff753dc249 libsystem_pthread.dylib`_pthread_start + 66
    frame #13: 0x00007fff753d840d libsystem_pthread.dylib`thread_start + 13
(lldb)
```
