### ISSUE TITLE
“Array.from(...).flat is not a function”

### ISSUE THREAD

**Issue by gilletteonmeheleparim** [urbit/urbit#3906]
Landscape on mobile Brave browser left me an error 
“Array.from(...).flat is not a function”

Stack trace
TypeError: Array.from(...).flat is not a function
    at r.value (http://159.89.27.103/~landscape/js/bundle/index.20fe6ee95061ade450fc.js:184:271039)
    at Pa (http://159.89.27.103/~landscape/js/bundle/index.20fe6ee95061ade450fc.js:37:69875)
    at Fa (http://159.89.27.103/~landscape/js/bundle/index.20fe6ee95061ade450fc.js:37:69670)
    at gs (http://159.89.27.103/~landscape/js/bundle/index.20fe6ee95061ade450fc.js:37:105469)
    at cl (http://159.89.27.103/~landscape/js/bundle/index.20fe6ee95061ade450fc.js:37:96716)
    at sl (http://159.89.27.103/~landscape/js/bundle/index.20fe6ee95061ade450fc.js:37:96641)
    at Js (http://159.89.27.103/~landscape/js/bundle/index.20fe6ee95061ade450fc.js:37:93671)
    at Ks (http://159.89.27.103/~landscape/js/bundle/index.20fe6ee95061ade450fc.js:37:90435)
    at jl (http://159.89.27.103/~landscape/js/bundle/index.20fe6ee95061ade450fc.js:37:111883)
    at http://159.89.27.103/~landscape/js/bundle/index.20fe6ee95061ade450fc.js:37:113126

**Comment by tylershuster** [comment]
What were you doing at the time?

**Comment by gilletteonmeheleparim** [comment]
I logged in and this appeared at the home screen

**Comment by matildepark** [comment]
Sounds like Leap crash. 

— 
~haddef-sigwen
https://urbit.org

**Comment by gilletteonmeheleparim** [comment]
error gone after I upgraded my Brave browser. I guess I hadn't updated it since 2019 version where Array.prototype.flat() wasn't supported yet
guess can be closed
