### ISSUE TITLE
Notifications show new notifications dot despite all being marked read

### ISSUE THREAD

**Issue by mike-cr** [urbit/urbit#3929]
**Describe the bug**
There's a blue dot next to the leap button despite all notifications being marked read. I think it might have got messed up by the since-fixed crash-on-remote-content bug

**To Reproduce**
1. Not sure...

**Expected behavior**
There should not be a blue dot if there are no unread notifications

**Desktop (please complete the following information):**
 - OS: Arch linux 64-bit
 - Browser qutebrowser (qtwebengine)
 - Base hash 0v14.pk93p.3v3pd.gomnc.ut49c.31ca7.aqqvh.sg72n.o24vc.qa0bk.tdo1o

**Comment by Fang-** [comment]
I got this too, even before seeing that remote content crash, so I don't think it's related.

**Comment by vvisigoth** [comment]
I've seen this but now can't repro @liam-fitzgerald what should we do if we see this in the wild to at least isolate if it's on front end or back end.

**Comment by matildepark** [comment]
I can reproduce this often; I fix it by archiving all the notifications I can see, then refresh and come back and there's my new notification. I think #3935 fixes this though.

**Comment by mike-cr** [comment]
I tried archiving everything and now it crashes:

```
Error
“Cannot read property 'group-path' of undefined”
Stack trace
TypeError: Cannot read property 'group-path' of undefined
    at by (https://landscape.tinnus-napbus.xyz/~landscape/js/bundle/index.b23d5c0044c48b1d2bab.js:184:263175)
    at Ko (https://landscape.tinnus-napbus.xyz/~landscape/js/bundle/index.b23d5c0044c48b1d2bab.js:37:57929)
    at gs (https://landscape.tinnus-napbus.xyz/~landscape/js/bundle/index.b23d5c0044c48b1d2bab.js:37:104168)
    at cl (https://landscape.tinnus-napbus.xyz/~landscape/js/bundle/index.b23d5c0044c48b1d2bab.js:37:96716)
    at sl (https://landscape.tinnus-napbus.xyz/~landscape/js/bundle/index.b23d5c0044c48b1d2bab.js:37:96641)
    at Js (https://landscape.tinnus-napbus.xyz/~landscape/js/bundle/index.b23d5c0044c48b1d2bab.js:37:93671)
    at https://landscape.tinnus-napbus.xyz/~landscape/js/bundle/index.b23d5c0044c48b1d2bab.js:37:45313
    at t.unstable_runWithPriority (https://landscape.tinnus-napbus.xyz/~landscape/js/bundle/index.b23d5c0044c48b1d2bab.js:45:3844)
    at qi (https://landscape.tinnus-napbus.xyz/~landscape/js/bundle/index.b23d5c0044c48b1d2bab.js:37:45022)
    at Wi (https://landscape.tinnus-napbus.xyz/~landscape/js/bundle/index.b23d5c0044c48b1d2bab.js:37:45258)
```

**Comment by matildepark** [comment]
Hmm. Another reproduction of the issue @urcades was facing ...

**Comment by mike-cr** [comment]
I had previously done :metadata-store [%cleanup ...] to get rid of some groups that hadn't been deleted properly, maybe it's related

**Comment by matildepark** [comment]
Ooo this is good info

**Comment by vvisigoth** [comment]
big if true
—
~poldec-tonteg
http://urbit.org

**Comment by mike-cr** [comment]
it seems there's a chat channel from a group I left that's still listed in chat-cli chats. :metadata-store [%cleanup ...] hasn't gotten rid of it and ;leave in chat-cli also does nothing. Is there a command that can properly purge this channel? I wonder whether it's this channel that's breaking notifications

**Comment by matildepark** [comment]
`:metadata-store [%cleanup` would actually cause the crash because it purges the metadata for the channel; but chat channels aren't opted-in by default to notifications unless they're DMs? Depending on the heuristic we used to identify DMs ...

**Comment by mike-cr** [comment]
hmmm the reason I ran `:metadata-store [%cleanup` was because when I left the group normally the disengrouped chat channel started showing up under DMs/drafts, so maybe it got subscribed to notifications when that happened

**Comment by mike-cr** [comment]
oh nice the new OTA seems to have fixed the problem somehow
