### ISSUE TITLE
Inviting when a Link collection is open throws an error

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#4001]
**Describe the bug**
With a link collection open, if I try to invite someone, I get a stack trace

**To Reproduce**
1. Go to a link collection
2. Click on the invite icon
3. See error

```
Error: Invalid integer: NaN is not a valid exponent.
    at U (https://ravmel-ropdyl.arvo.network/~landscape/js/bundle/index.c099f574cf3ccea90625.js:3:20838)
    at V (https://ravmel-ropdyl.arvo.network/~landscape/js/bundle/index.c099f574cf3ccea90625.js:3:21497)
    at a (https://ravmel-ropdyl.arvo.network/~landscape/js/bundle/index.c099f574cf3ccea90625.js:3:2065)
    at render (https://ravmel-ropdyl.arvo.network/~landscape/js/bundle/index.c099f574cf3ccea90625.js:184:173844)
    at https://ravmel-ropdyl.arvo.network/~landscape/js/bundle/index.c099f574cf3ccea90625.js:88:439645
    at gs (https://ravmel-ropdyl.arvo.network/~landscape/js/bundle/index.c099f574cf3ccea90625.js:37:107582)
    at cl (https://ravmel-ropdyl.arvo.network/~landscape/js/bundle/index.c099f574cf3ccea90625.js:37:96716)
    at sl (https://ravmel-ropdyl.arvo.network/~landscape/js/bundle/index.c099f574cf3ccea90625.js:37:96641)
    at Js (https://ravmel-ropdyl.arvo.network/~landscape/js/bundle/index.c099f574cf3ccea90625.js:37:93671)
    at https://ravmel-ropdyl.arvo.network/~landscape/js/bundle/index.c099f574cf3ccea90625.js:37:45313
```

**Expected behavior**
The invite box

**Screenshots**
<img width="1097" alt="Screen Shot 2020-11-23 at 9 27 42 AM" src="https://user-images.githubusercontent.com/1467211/99994810-5e7f8500-2d6e-11eb-9d0a-3dfd8425a80f.png">

**Comment by matildepark** [comment]
This is fixed in https://github.com/urbit/urbit/pull/3995.
