### ISSUE TITLE
homebrew installation didn't work for me

### ISSUE THREAD

**Issue by ault011** [urbit/urbit#499]
I tried to use homebrew to install urbit in another
folder, but this happened:

```
jhca:~ henry1$ cd test-urbit/
jhca:test-urbit henry1$ brew install --HEAD homebrew/head-only/urbit
Error: undefined method `desc' for Urbit:Class
Please report this bug:
    http://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-head-only/urbit.rb:2:in `<class:Urbit>'
/usr/local/Library/Taps/homebrew/homebrew-head-only/urbit.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/formulary.rb:65:in `klass'
/usr/local/Library/Homebrew/formulary.rb:50:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:185:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:198:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:30:in `install'
/usr/local/Library/brew.rb:136:in `<main>'
```

If I put in effort, I could probably figure out what's wrong, but
it should be seamless, no?

**Comment by galenwp** [comment]
https://github.com/Homebrew/homebrew/issues/41882
