### ISSUE TITLE
Booting a fake zod on master a second time crashes

### ISSUE THREAD

**Issue by jfranklin9000** [urbit/urbit#827]
urbit/urbit commit: `dd055b459802366829abef362794e80bac95471a` `Don't crash without -B.`
urbit/arvo commit: `35d174565f5a0301070313c33d2199737103a66a` `Merge remote-tracking branch 'ohaitch/fix-diffs' Closes #357`
latest.pill: `35d174565f5a0301070313c33d2199737103a66a.pill`

`bin/urbit -c -F -I zod -A arvo -B latest.pill fakezod`

In `u3_pier_create()` `u3_Host.ops_u.arv_c` is (pointer to string) `arvo`.

Solid:

`.urbit/pill +metal ~zod` to create `fakezod/.urb/put/urbit.pill`.

(`CONTRIBUTING.md` says `.urbit/pill +solid` but this does not create a pill.)

Quit and restart:

`bin/urbit -F -I zod fakezod`

In `u3_pier_create()` `u3_Host.ops_u.arv_c` is `0x0` so
`pir_u->arv_c = c3_malloc(1 + strlen(u3_Host.ops_u.arv_c));`
leads to `address 0x0 out of loom!`.

**Comment by joemfb** [comment]
It works if you just reuse the exact args that you used to create the fake-zod. (This is weird and not right, but a working solution while master is in flux...)

**Comment by juped** [comment]
if you patch it for me, it's fine, but i'm not interested in doing it myself since i've already taken out all the command line options in work-in-progress, which is way behind schedule

**Comment by jimdigriz** [comment]
Is master currently broken, and Joe Public should just keep with the 0.4.x releases?

I have no 'pill' file and just starting fresh building 83d0f88710953d0674b0e8da15ae39721c218228 with DEBUG=yes and I get:
````
alex@quatermain:/usr/src/urbit$ ./bin/urbit -F -c mycomet
~
urbit 0.5-devel
urbit: home is mycomet
loom: mapped 2048MB
boot: installed 423 jets
lite: arvo formula 651372b4
hoon-assembly
arvo-boot
lite: core 77ffbb6c
lite: final state 6fa012e6
cmd socket up
boot mycomet 
address (nil) out of loom!
loom: [0x36000000 : 0xb6000000)

bail: oops
Aborted (core dumped)
````

````
alex@quatermain:/usr/src/urbit$ gdb ./bin/urbit core 
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./bin/urbit...done.
[New LWP 3630]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./bin/urbit -F -c mycomet'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fa9c4c7b067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007fa9c4c7b067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fa9c4c7c448 in __GI_abort () at abort.c:89
#2  0x00000000004153e4 in u3m_bail (how=1936748399) at noun/manage.c:632
#3  0x00000000004154f2 in c3_cooked () at noun/manage.c:669
#4  0x000000000040cd6c in u3e_fault (adr_v=0x0, ser_i=1) at noun/events.c:126
#5  0x00007fa9c60c0eaf in ?? () from /usr/lib/x86_64-linux-gnu/libsigsegv.so.2
#6  <signal handler called>
#7  strlen () at ../sysdeps/x86_64/strlen.S:106
#8  0x000000000045ead0 in u3_pier_create (pax_c=0x134fad0 "mycomet", sys_c=0x134fba0 "") at vere/pier.c:1265
#9  0x000000000045fb56 in _pier_boot_make (pax_c=0x134fad0 "mycomet", sys_c=0x134fba0 "") at vere/pier.c:1821
#10 0x000000000045fb8f in u3_pier_boot (pax_c=0x134fad0 "mycomet", sys_c=0x134fba0 "", pep_u=0x360003b0)
    at vere/pier.c:1835
#11 0x000000000045b79c in _king_boot (boot=3221225847) at vere/king.c:228
#12 0x000000000045b543 in _king_doom (doom=3221225810) at vere/king.c:206
#13 0x000000000045afbb in _king_fate (vod_p=0x0, mat=2147483871) at vere/king.c:113
#14 0x0000000000450f22 in _newt_consume (mot_u=0x36000230) at vere/newt.c:190
#15 0x00000000004510b6 in _newt_read_cb (str_u=0x36000230, len_i=29, buf_u=0x7ffcc16510b0) at vere/newt.c:245
#16 0x00007fa9c69a9764 in ?? () from /usr/lib/x86_64-linux-gnu/libuv.so.1
#17 0x00007fa9c69a9eec in ?? () from /usr/lib/x86_64-linux-gnu/libuv.so.1
#18 0x00007fa9c69aed8a in ?? () from /usr/lib/x86_64-linux-gnu/libuv.so.1
#19 0x00007fa9c69a0938 in uv_run () from /usr/lib/x86_64-linux-gnu/libuv.so.1
#20 0x000000000045be51 in u3_king_commence () at vere/king.c:431
#21 0x0000000000448d74 in main (argc=4, argv=0x7ffcc16545e8) at vere/main.c:548
(gdb) 
````

**Comment by juped** [comment]
It's not exactly broken, but you do need a pill file (easiest way: https://bootstrap.urbit.org/master.pill), and Joe Public should indeed stick to the 0.4.x releases.
