### ISSUE TITLE
mug mismatch in _ce_patch_verify()

### ISSUE THREAD

**Issue by jfranklin9000** [urbit/urbit#843]
Running maintenance 0.4.5 results in a mug mismatch:

````
$ bin/urbit ../PLANETS/pinmul-mopfer
~
urbit 0.4.5
urbit: home is ../PLANETS/pinmul-mopfer
loom: mapped 2048MB
_ce_patch_verify: mug mismatch 17396/768; (31570b5d, 177e02ac)

bail: oops
[New Thread 0x1913 of process 8650]

Thread 1 received signal SIGABRT, Aborted.
0x00007fff97f7df06 in ?? () from /usr/lib/system/libsystem_kernel.dylib
(gdb) bt
#0  0x00007fff97f7df06 in ?? () from /usr/lib/system/libsystem_kernel.dylib
#1  0x00007fff8cba94ec in pthread_kill () from /usr/lib/system/libsystem_pthread.dylib
#2  0x00007fff90bc36df in abort () from /usr/lib/system/libsystem_c.dylib
#3  0x0000000100017926 in u3m_bail (how=1936748399) at noun/manage.c:632
#4  0x0000000100017c52 in c3_cooked () at noun/manage.c:669
#5  0x000000010000c2f9 in _ce_patch_verify (pat_u=0x101100040) at noun/events.c:330
#6  0x000000010000d21b in _ce_patch_open () at noun/events.c:394
#7  0x000000010000c9a1 in u3e_live (nuu_o=1 '\001', dir_c=0x101100000 "../PLANETS/pinmul-mopfer")
    at noun/events.c:858
#8  0x000000010001a78b in u3m_boot (nuu_o=1 '\001', bug_o=1 '\001', 
    dir_c=0x101100000 "../PLANETS/pinmul-mopfer", pil_c=0x0) at noun/manage.c:1583
#9  0x000000010005c173 in main (argc=2, argv=0x7fff5fbffc38) at vere/main.c:541
````

In `noun/manage.c:_ce_patch_verify()` `pat_u->con_u->pgs_w` is `955`, and `i_w` is `768`.

````
$ ls -l ../PLANETS/pinmul-mopfer/.urb/chk
total 757040
-rw-r--r--  1 jmf  staff       7664 May 26 15:27 control.bin
-rw-r--r--  1 jmf  staff   12582912 May 26 15:27 memory.bin
-rw-r--r--  1 jmf  staff  374996992 May 26 15:26 north.bin
-rw-r--r--  1 jmf  staff      16384 May 26 15:26 south.bin
````

````
$ hexdump -C ../PLANETS/pinmul-mopfer/.urb/chk/memory.bin | tail
00bfff70  93 f4 3e c4 06 00 00 00  06 00 00 00 01 00 00 00  |..>.............|
00bfff80  bf 23 c3 0e 26 98 3e 84  50 33 00 00 06 00 00 00  |.#..&.>.P3......|
00bfff90  06 00 00 00 01 00 00 00  59 23 68 41 00 00 00 00  |........Y#hA....|
00bfffa0  00 00 00 00 06 00 00 00  06 00 00 00 01 00 00 00  |................|
00bfffb0  05 26 0b 47 35 33 57 84  f2 2f 3f c4 06 00 00 00  |.&.G53W../?.....|
00bfffc0  06 00 00 00 01 00 00 00  1f 3d 48 42 e7 5b 36 84  |.........=HB.[6.|
00bfffd0  f0 5b 36 c4 06 00 00 00  06 00 00 00 01 00 00 00  |.[6.............|
00bfffe0  9e 94 15 0e 95 7f 25 83  09 39 00 00 06 00 00 00  |......%..9......|
00bffff0  06 00 00 00 01 00 00 00  62 4b ea 64 d8 86 c3 c4  |........bK.d....|
00c00000
````

I had a power outage and `~pinmul-mopfer` *might* have been running
so I theorize that `memory.bin` has been truncated.

I'll keep this planet untouched in case we want to investigate this.

But if I wanted to clear this up could I simply delete
`memory.bin` and `control.bin` and restart urbit?

**Comment by cgyarvin** [comment]
Interesting.  My conclusion is that you got a power outage during a save
and the outage handling of the checkpoint process isn't quite perfect.
That's good to know, thanks for accidentally testing!

The correct way to clear the checkpoint is rm -rf .urb/chk.  Then you get
to find out whether your event log is corrupt, too!  I am definitely not
confident in the integrity of the old event database.

**Comment by jfranklin9000** [comment]
I deleted chk/ and after an 8 hour playback it worked!

Since this was on maintenance I won't worry about this anymore,
but I should probably get a UPS.

**Comment by cgyarvin** [comment]
I always love it when those long playbacks work.  Which they generally do,
in fact,.

A UPS shouldn't be required but doesn't hurt!  The thing is, not only is
writing reliable persistence code subject to all sorts of OS/FS vagaries,
it's also subject to "Tso's law," ie, "all PC hardware is crap."

**Comment by lukebuehler** [comment]
This just happened to me too. My VM on Azure was restarted and then I got the following:

```
urrbitone@urbitone:~/urbit$ urbit lavlyn-litmeg
~
urbit 0.4.3
urbit: home is lavlyn-litmeg
loom: mapped 2048MB
_ce_patch_verify: mug mismatch 0/0; (286e3169, 4a3aa73e)

bail: oops
Aborted (core dumped)
```

I will now, try the suggested fixes here and will report back.

**Comment by jtobin** [comment]
Closing this one as it is both dated and apparently resolved.
